
import java.util.Arrays;
import javax.naming.directory.SearchResult;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Usuario
 */
public class ComprobacionNumerica extends javax.swing.JFrame {

    /**
     * Creates new form ComprobacionNumerica
     */
    public ComprobacionNumerica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulo = new javax.swing.JLabel();
        lblingresar = new javax.swing.JLabel();
        comprobar = new javax.swing.JButton();
        txtingresarnumero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulo.setText("COMPROBACIÓN DE NÚMEROS ENTEROS");

        lblingresar.setText("Ingrese un numero ");

        comprobar.setText("Comprobar");
        comprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobarActionPerformed(evt);
            }
        });

        txtingresarnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtingresarnumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblingresar)
                        .addGap(69, 69, 69)
                        .addComponent(txtingresarnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(comprobar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(lbltitulo)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbltitulo)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblingresar)
                    .addComponent(txtingresarnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comprobar))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void comprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobarActionPerformed
        int numero = Integer.parseInt(txtingresarnumero.getText());
        if (numero >= 1 && numero <= 500) {
            //PERFECTOS
            this.numerosPerfectos(numero);
            this.sumaPrimosMenores(this.numerosPrimos(numero), numero);
        }else{
            JOptionPane.showMessageDialog(this,"Ingrese un número del 1 al 500" );
        }
            txtingresarnumero.setText("");
    }//GEN-LAST:event_comprobarActionPerformed
    public void numerosPerfectos(int numero) {
        int cont = 0;
        for (int i = 1; i < numero; i++) {
            if ((numero % i) == 0) {
                cont += i;
            }
        }
        if (cont == numero) {
            JOptionPane.showMessageDialog(this, "Es perfecto");
        } else {
            JOptionPane.showMessageDialog(this, "No es un número perfecto");
        }
    }

    public boolean numerosPrimos(int numero) {
        String primos = "";
        int p = 0;
        for (int i = 1; i <= numero; i++) {
            if ((numero % i) == 0) {
                primos += i + "-";
                System.out.println("----" + primos);
            }
        }
        String[] n = primos.split("-");
        if (n.length == 2) {
            for (String s : n) {
                if (Integer.parseInt(s) == 1 || Integer.parseInt(s) == numero) {
                    p++;
                }
            }
        }
        if (p == 2) {
            JOptionPane.showMessageDialog(this, "Es primo");
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "No es un número primo");
            return false;
        }
    }

    public void sumaPrimosMenores(boolean n, int numero) {
        int sum = 0;
        String imprimir = "";
        int[] numPrimos = {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499};
        for (int numPrimo : numPrimos) {
            System.out.println("||||" + numPrimo + ">=" + numero);
            if (numPrimo >= numero) {
                JOptionPane.showMessageDialog(this, "Listado # Primos Menores:"+"\n"+imprimir);
                JOptionPane.showMessageDialog(this, "La sumatoria de los números Primos Menores es:" + sum + "\n"
                        + "La raíz cuadrada es:" + Math.sqrt(sum));
                break;
            } else {
                imprimir += numPrimo + "+";
                sum += numPrimo;
                System.out.println("******" + imprimir + "$" + sum);
            }
        }

    }


    private void txtingresarnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtingresarnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtingresarnumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprobacionNumerica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprobacionNumerica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprobacionNumerica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprobacionNumerica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprobacionNumerica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comprobar;
    private javax.swing.JLabel lblingresar;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTextField txtingresarnumero;
    // End of variables declaration//GEN-END:variables
}
